<a href="https://colab.research.google.com/github/jahelsantiago/Pytorch-tutorial/blob/main/troch_init.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch 
from __future__ import print_function

Los tensores son matrices que pueden correr en la GPU

# BASICOS

## OPERACIONES DE CREACION

In [ ]:
#create a tensor of random numbers
x = torch.rand(size = (5,5))
print(x)

tensor([[0.4931, 0.4747, 0.2496, 0.2817, 0.4045],
        [0.8887, 0.6977, 0.6275, 0.3882, 0.9992],
        [0.5645, 0.1571, 0.0433, 0.2362, 0.8521],
        [0.5724, 0.9014, 0.1203, 0.4840, 0.4813],
        [0.2360, 0.9794, 0.0962, 0.4657, 0.1885]])


In [ ]:
#create a tensor of ones
x = torch.ones(size = (3,3))
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
#create a tensor of zeros
x = torch.zeros(size = (3,3))
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
#create a tensor of the values
x = torch.tensor([1,1.2,0])
print(x)

tensor([1.0000, 1.2000, 0.0000])


In [ ]:
x = torch.ones((3,4))
print(x)
x = torch.rand_like(x) # con el _like podemos copiar un tensor con el mismo tamaño
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0.8807, 0.1475, 0.7237, 0.8859],
        [0.5809, 0.9098, 0.9362, 0.2553],
        [0.4155, 0.7174, 0.0472, 0.3477]])


In [ ]:
# obtener el tamaño de un tensor
print(x.size())

torch.Size([3, 4])


## OPERACIONES MATEMATICAS 

In [ ]:
a = torch.empty((3,3)) #empty tensor
b = torch.zeros((3,3)) 
a = b+1 #add 1 
a *= 3 # multiply 
print(a)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])


##resize

In [ ]:
x = torch.tensor(list(range(1,10)))
print(x)
print(x.view((3,3)))
print(x.view((-1,3)))

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [ ]:
x = torch.rand(1)
print(x)
print(x.item())


tensor([0.3172])
0.31718599796295166


## Numpy

In [ ]:
import numpy as np
a = np.ones((3,3))
x = torch.from_numpy(a)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [ ]:
b = torch.randint(1,100,(3,3))
b.numpy()

array([[79, 75, 53],
       [24, 70, 62],
       [10, 17, 56]])

# Gradients

In [ ]:
import torch 
x = torch.ones([3,3], requires_grad= True)
print(x)
y = x**2 + x -1
print(y)
z = y.mean()
print(z)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], grad_fn=<SubBackward0>)
tensor(1., grad_fn=<MeanBackward0>)


In [ ]:
x = torch.rand((3,3))
print(x.requires_grad)
x.requires_grad_(True)
print(x.requires_grad)

False
True


#Neural networks contruction

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module): #todas las redes deben heredar de la clase Module
  def __init__(self):
    super(Net, self).__init__()

    self.conv1 = nn.Conv2d(in_channels=1, out_channels=6, kernel_size=(3,3))
    self.Conv2 = nn.Conv2d(6, 16, 3)    

    self.fc1 = nn.Linear(6*6*16, 120)
    self.fc2 = nn.Linear(120, 84)
    self.fc3 = nn.Linear(84,10)

  def forward(self, x):
    x = F.max_pool2d(F.relu(self.conv1(x)), (2,2))
    x = F.max_pool2d(F.tanh(self.Conv2(x)), 2)

    x = x.view(-1, self.num_flat_features(x))
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.fc3(x)

    return x

  def num_flat_features(self, x):
      size = x.size()[1:]  # all dimensions except the batch dimension      
      num_features = 1
      for s in size:
          num_features *= s
      return num_features


net = Net()
print(net)



Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (Conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [2]:
parameter = list(net.parameters())[0]
print(parameter)
print(parameter.size())

Parameter containing:
tensor([[[[ 0.1952,  0.2786, -0.2585],
          [-0.2058, -0.2113,  0.1851],
          [-0.1757,  0.2921, -0.0074]]],


        [[[ 0.2171, -0.1308,  0.2363],
          [ 0.0530, -0.3191, -0.0937],
          [ 0.1209, -0.2094,  0.2543]]],


        [[[ 0.0291,  0.2415,  0.2558],
          [ 0.1525, -0.1037, -0.2917],
          [-0.1796, -0.0422,  0.1524]]],


        [[[-0.0583, -0.3271,  0.1325],
          [ 0.1876, -0.0572,  0.1784],
          [-0.1220,  0.1425,  0.2620]]],


        [[[-0.3324, -0.2457, -0.3032],
          [ 0.0147, -0.0650, -0.1678],
          [-0.2887,  0.0704,  0.2040]]],


        [[[ 0.1369,  0.0729, -0.2261],
          [-0.2276, -0.2674,  0.1106],
          [ 0.0502, -0.2851,  0.2665]]]], requires_grad=True)
torch.Size([6, 1, 3, 3])


In [3]:
inp = torch.randn(1,1,32,32)
out = net(inp)
print(out)

tensor([[-0.0904, -0.1186,  0.1220,  0.0137,  0.1261, -0.0324, -0.0631, -0.0580,
         -0.0699, -0.0804]], grad_fn=<AddmmBackward>)


/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:1628: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")


## Loss function

In [5]:
inp = torch.rand(1,1,32,32) # generate random input 
out = net(inp) #porcess troght forward
print("models output")
print(out)
print("---------------------------------------")
y = torch.randn(10) #generate 10 classes for the label
y = y.view(1,-1)
print("labels")
print(y)
print("---------------------------------------")
print("loss")
criteria = nn.MSELoss()
loss = criteria(out, y)
print(loss)



models output
tensor([[-0.0921, -0.0965,  0.1072,  0.0069,  0.1121, -0.0399, -0.0921, -0.0659,
         -0.0677, -0.1036]], grad_fn=<AddmmBackward>)
---------------------------------------
labels
tensor([[-1.7129,  0.6977,  0.0286, -1.2860, -0.0785, -2.1006,  1.0439,  1.0402,
         -0.8662, -1.7480]])
---------------------------------------
loss
tensor(1.5073, grad_fn=<MseLossBackward>)


/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:1628: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")


In [6]:
net.zero_grad()
print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)

loss.backward()

print("conv1.bias.grad after backward")
print(net.conv1.bias.grad)

conv1.bias.grad before backward
tensor([0., 0., 0., 0., 0., 0.])
conv1.bias.grad after backward
tensor([ 0.0452, -0.0033, -0.0014, -0.0074, -0.0050, -0.0445])


## Update parametres

stochastic gradient desent

In [21]:
print("conv1.bias before update")
print(net.conv1.bias)

learning_rate = 0.01
for f in net.parameters():
    f.data = f.data - f.grad.data * learning_rate

print("conv1.bias after update")
print(net.conv1.bias)    

conv1.bias before update
Parameter containing:
tensor([ 0.3303, -0.3110, -0.2361,  0.0318,  0.2651,  0.0822],
       requires_grad=True)
conv1.bias after update
Parameter containing:
tensor([ 0.3298, -0.3110, -0.2360,  0.0318,  0.2652,  0.0826],
       requires_grad=True)


# optimizers

In [26]:
import torch.optim as optim

optimizer = optim.Adam(net.parameters(), lr = 0.001)

for i in range(5):
  optimizer.zero_grad() #convertimos el gradiente en 0 
  output = net(inp)  
  loss = criteria(output, y)
  loss.backward()
  optimizer.step()
  

/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:1628: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
